<template>
    <svg
        viewBox="0 0 14 14"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        aria-hidden="true"
        class="size-[1.4rem]"
    >
        <rect
            x="1.5"
            y="1.5"
            width="5"
            height="5"
            rx="0.8"
            stroke="currentColor"
            stroke-width="1.2"
        />
        <rect
            x="7.5"
            y="1.5"
            width="5"
            height="5"
            rx="0.8"
            stroke="currentColor"
            stroke-width="1.2"
        />
        <rect
            x="1.5"
            y="7.5"
            width="5"
            height="5"
            rx="0.8"
            stroke="currentColor"
            stroke-width="1.2"
        />
        <rect
            x="7.5"
            y="7.5"
            width="5"
            height="5"
            rx="0.8"
            stroke="currentColor"
            stroke-width="1.2"
        />
    </svg>
</template>